### ISSUE TITLE
Black screen while "sudo service peppymeter start"

### ISSUE THREAD

**Issue by Jacob9Audio** [FdeAlexa/PeppyMeter_and_moOde#2]
Hi,
My hardware setup is Pi 3B+ with DAC HiFiBerry DAC+ <==> HDMI 1920x1080 display.
Moode version 7.2.0

Beforehand, I can success run the PeppyMeter shown on my PC by using the command "sudo python3 peppymeter.py"
Now, I start to make it auto run after boot and follow the "Creation of scripts & service" chapter.
In the "Service" session and run the command below. 
==> The screen turn to black after 20 sec. Get back to Moode UI while stop the service.

### Here I have Moode UI playing radio station

pi@moode:~ $ sudo systemctl start peppymeter.service
pi@moode:~ $ sudo service peppymeter status
● peppymeter.service - PeppyMeter, start a virtual VU Meter display
   Loaded: loaded (/etc/systemd/system/peppymeter.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2023-02-21 03:20:52 EST; 2s ago
 Main PID: 1567 (peppySER.sh)
    Tasks: 2 (limit: 2063)
   CGroup: /system.slice/peppymeter.service
           ├─1567 /bin/sh /home/pi/PeppyMeter/peppySER.sh
           └─1568 sleep 20

### After 20 second, the screen turns to black 

pi@moode:~ $ sudo service peppymeter stop
### HDMI display screen come back to Moode UI Playing radio station.

I am thinking if the error log make this problem ==> 
Feb 21 03:21:13 moode peppySER.sh[1567]: libpng warning: iCCP: known incorrect sRGB profile
But I can see the PeppyMeter on my desktop with this error log in the first place.

Maybe screen size is the problem?

Appreciate if any suggestion.

**Comment by FdeAlexa** [comment]
Hello Jacob,
I have to build up an environment similar to yours: please give me some time to try to replicate the problem.
A couple of notes:
.) there is a dedicated section in this Github to automatically start PeppyMeter with moOde.
.) I suggest to update moOde (now 8.2.5): the instructions are the same of 7.2.
Best regards and thanks,
Francesco

**Comment by FdeAlexa** [comment]
Hello Jacob,
It would appear that the peppySER.sh file is incorrect: could you please report the result of the following command:
cat /home/pi/PeppyMeter/peppySER.sh
Best regards and thanks,
Francesco

**Comment by Jacob9Audio** [comment]
I will get back to you tomorrow. 
I give a last try before I leave the working bench, I force display resolution to 800x600 and it seems works. Have to check more detail and get you peppySER.sh tomorrow.
Appreciate the timely response

**Comment by Jacob9Audio** [comment]
Here is the cat peppySET.sh

pi@moode:~/PeppyMeter $ cat peppySER.sh
#!/bin/sh
sleep 20 && cd /home/pi/PeppyMeter && sudo python3 peppymeter.py

**Comment by Jacob9Audio** [comment]
Sorry, I give wrong information on display resolution.
I use fbset command check the result. My initial display resolution is **1280x800**. 
And it shows black screen but 800x600 works fine.

Below are the procedure I have done again.

// set HDMI to auto detect.  hdmi_group=0 in /boot/config.txt and reboot
// Play a radio station on Moode
pi@moode:~ $sudo service peppymeter start
// Display show black screen.
pi@moode:~ $ fbset
mode "1280x800"
    geometry 1280 800 1280 800 32
    timings 0 0 0 0 0 0 0
    rgba 8/16,8/8,8/0,8/24
endmode
pi@moode:~ $sudo service peppymeter stop
// Display show Moode UI


// set HDMI (800x600).  hdmi_group=2 and hdmi_model=9 in /boot/config.txt and reboot 
// Play a radio station on Moode
pi@moode:~ $sudo service peppymeter start
// Display show Moode UI
// After 20 sec, display show PeppyMeter
pi@moode:~/PeppyMeter $ fbset
mode "800x600"
    geometry 800 600 800 600 32
    timings 0 0 0 0 0 0 0
    rgba 8/16,8/8,8/0,8/24
endmode

I check the supported resulution on PeppyMeter.doc wiki.
==> UI is available in four resolutions 320x240, 480x320, 800x480 and 1280x400 pixels.

Now I am a bit confused. Not sure where the problem comes from.

**Comment by Jacob9Audio** [comment]
I think I found the problem.
While my screen is 1280x800. The PeppyMeter/config.txt should config to **meter.size = wide**
Thanks for the help.

BTW, I also re-flash the moode 8.2.5 and follow the instruction. it works fine as well.
