### ISSUE TITLE
The PeppyMeter stop working afterI remove the USB mouse

### ISSUE THREAD

**Issue by Jacob9Audio** [FdeAlexa/PeppyMeter_and_moOde#3]
Hi,
My hardware setup is Pi 3B+ with DAC HiFiBerry DAC+ <==> HDMI 1280x720 display.
Moode version 8.2.5.
I found while the USB mouse is connected, everything is fine with auto start.
AfterI disconnect the USB mouse and reboot,  the PeppyMeter won't show anymore.

Any suggestion is appreciated~~

Below is the status of the fda_autopeppy service:

pi@moode:~ $ sudo service fda_autopeppy status
● fda_autopeppy.service - FdA Service to start PeppyMeter at PLAY
     Loaded: loaded (/etc/systemd/system/fda_autopeppy.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-02-23 03:36:15 EST; 1min 25s ago
   Main PID: 408 (python3)
      Tasks: 4 (limit: 2058)
        CPU: 6.184s
     CGroup: /system.slice/fda_autopeppy.service
             ├─ 408 python3 fda_autopeppy.py
             ├─1493 sudo python3 /home/pi/PeppyMeter/peppymeter.py
             └─1494 python3 /home/pi/PeppyMeter/peppymeter.py

Feb 23 03:36:32 moode python3[935]:     pygame.display.init()
Feb 23 03:36:32 moode python3[935]: pygame.error: Unable to open mouse
Feb 23 03:37:14 moode python3[1494]: pygame 1.9.6
Feb 23 03:37:14 moode python3[1494]: Hello from the pygame community. https://www.pygame.org/contribute.html
Feb 23 03:37:14 moode python3[1494]: Traceback (most recent call last):
Feb 23 03:37:14 moode python3[1494]:   File "/home/pi/PeppyMeter/peppymeter.py", line 293, in <module>
Feb 23 03:37:14 moode python3[1494]:     pm.init_display()
Feb 23 03:37:14 moode python3[1494]:   File "/home/pi/PeppyMeter/peppymeter.py", line 148, in init_display
Feb 23 03:37:14 moode python3[1494]:     pygame.display.init()
Feb 23 03:37:14 moode python3[1494]: pygame.error: Unable to open mouse

**Comment by FdeAlexa** [comment]
A mouse or a touch screen is needed to change the status of the display from PeppyMeter to MoOde.
If you need to work without it, you can try with the service instead of autopeppy and disable the mouse in the config.txt (mouse.enabled = False instead of mouse.enabled = True).
Regards,
Francesco

**Comment by Jacob9Audio** [comment]
Thanks Francesco.

I found set the "Wake on Play" can work normally without mouse.
My goal is use phone browser as player and the screen just show the nice PeppyMeters.
I still have a final goal to enable the PeppyMeter in real "Wide" screen like 1920x480 but the meter is always scaling only in the middle of the screen. I guess I have to modify PeppyMeter to support 1920x480 to make the screen nicer.

Any suggestion is appreciated~~
