### ISSUE TITLE
PeppyMeter, moOde and Roon?

### ISSUE THREAD

**Issue by glc650** [FdeAlexa/PeppyMeter_and_moOde#4]
I followed your guide and got PeppyMeter working on moOde on a RPi4B with [this](https://www.amazon.com/dp/B0B455LDKH) display when using a USB DAC with the RPi.  When I try using the same setup as a Roon zone, the needle never moves on the VU meter.  I tried selecting the DAC as well as both Loopbacks that appear to Roon.

Thanks,
->g.

**Comment by FdeAlexa** [comment]
Hi glc650,
I don't know Roon: anyway let's try to troubleshoot.
What does it happen if you run (during music play):

/home/pi/peppyalsa/src/peppyalsa-client /var/tmp/peppyfifo 

If you don't see any moving bars, please send the result of

cat /etc/alsa/conf.d/_sndaloop.conf

Regards,
Francesco

**Comment by glc650** [comment]
If I just use moode to play music (no Roon), I see bars.

If I use Roon to play music through moode, no bars.

```
#
# This file provides a default Loopback device by overriding the _audioout device defined in /etc/alsa/conf.d/
#
# The trailing underscores are removed/added by job "alsa_loopback" to effectively turn the override On/Off.
# This job is submitted by snd-config.php and corresponds to the setting "ALSA loopback ON/OFF".
#
pcm.!_audioout {
type plug
slave.pcm {
type multi
slaves {
a { channels 2 pcm "plughw:1,0" }
#b { channels 2 pcm "hw:Loopback,0" }
b { channels 2 pcm "pippopeppy" }        # Loopback via peppy output
}
bindings {
0 { slave a channel 0 }
1 { slave a channel 1 }
2 { slave b channel 0 }
3 { slave b channel 1 }
}
}
ttable [
[ 1 0 1 0 ]   # left  -> a.left,  b.left
[ 0 1 0 1 ]   # right -> a.right, b.right
]
}
pcm.pippopeppy {
        type meter
        slave.pcm "hw:Loopback,0"
        scopes.0 peppyalsa
}

pcm_scope.peppyalsa {
        type peppyalsa
        decay_ms 400
        meter "/var/tmp/peppyfifo"
        meter_max 100
        meter_show 0
}

pcm_scope_type.peppyalsa {
        lib /usr/local/lib/libpeppyalsa.so
}
```

**Comment by FdeAlexa** [comment]
HI,
as you probably already doubted, I think, after all day testing, the problem may be in the management of the loopback. As you know I'm not the author of PeppyMeter but I only dealt with the integration in moode.
You could try asking on the PeppyMeter thread on diyAudio (https://www.diyaudio.com/community/threads/peppymeter.291010).
I'm sorry I can't help you.
Best regards,
Francesco

**Comment by glc650** [comment]
> You could try asking on the PeppyMeter thread on diyAudio

I'll give that a try, thanks.
