### ISSUE TITLE
ambiguity in wording of 2_moOde.md

### ISSUE THREAD

**Issue by TheOldPresbyope** [FdeAlexa/PeppyMeter_and_moOde#6]
The current page reads

-----
At this point we have to patch an important file that contributes to the creation of the moOde MPD configuration: this file is different for each moOde release: now let's choose which release we are using.

    [moOde 6.7.1](https://github.com/FdeAlexa/PeppyMeter_and_moOde/blob/main/2_1_moOde671.md)
    [moOde 7.0.1](https://github.com/FdeAlexa/PeppyMeter_and_moOde/blob/main/2_2_moOde701.md)
    [moOde 7.1.0](https://github.com/FdeAlexa/PeppyMeter_and_moOde/blob/main/2_3_moOde710.md)
    [moOde 7.2.0](https://github.com/FdeAlexa/PeppyMeter_and_moOde/blob/main/2_4_moOde720.md)
-----

This leaves open two interpretations
1. the file has to be patched if and only we're working with one of these 4 releases, or
2. the file has to be patched for every release but the list of releases here is out-of-date and needs to be updated to include releases up to whatever is the current release (8.3.7 at this writing)

I suggest the page be modified to make clear to the reader what must be done.

**Comment by FdeAlexa** [comment]
Thanks, Kent, for the suggestion.  Modified with 7.20 and later.
Thanks again,
Francesco

**Comment by FdeAlexa** [comment]
Thanks and best regards,
Francesco
